version: '3.7'
services:
  dashboard:
    build:
      context: ./
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports:
      - 8080:80
    volumes:
      - "$PWD:/workspace"
    networks:
      - network 
    
networks:
  network:
    driver: bridge